namespace Sensum.Framework.Growtopia.Entities.Enums;

public enum AuthenticationError
{
    Unknown0,
    Unknown1,
    Unknown2,
    Unknown3,
    Unknown4,
    Unknown5,
    Unknown6, // Causes request to re-logon so maybe login packet invalid
    Unknown7,
    Unknown8,
    SubServersSyncing,
    Unknown10,
    Unknown11,
    Unknown12,
    Unknown13,
    Suspend,
    Banned,
    Unknown16,
    TooManyPeopleLogging,
    Unknown18,
    Unknown19,
    Unknown20,
    Unknown21,
    Unknown22,
    Maintenance,
    Unknown24,
    DeviceBan,
    Unknown26,
    Unknown28,
    GameUpdate,
    BadGuestName,
    Unk30,
    Unk31,
    Unk32,
    Unk33,
    Unk34,
    WrongCredentials,
    GuestLimitReached
}