namespace Sensum.Framework.Growtopia.Entities.Enums;

public enum GamePacketType : byte
{
    State = 0, // Hex[0x0], Decimal[0]
    CallFunction, // Hex[0x1], Decimal[1]
    UpdateStatus, // Hex[0x2], Decimal[2]
    TileChangeRequest, // Hex[0x3], Decimal[3]
    SendMapData, // Hex[0x4], Decimal[4]
    SendTileUpdateData, // Hex[0x5], Decimal[5]
    SendTileUpdateDataMultiple, // Hex[0x6], Decimal[6]
    TileActivateRequest, // Hex[0x7], Decimal[7]
    TileApplyDamage, // Hex[0x8], Decimal[8]
    SendInventoryState, // Hex[0x9], Decimal[9]
    ItemActivateRequest, // Hex[0xA], Decimal[10]
    ItemActivateObjectRequest, // Hex[0xB], Decimal[11]
    SendTileTreeState, // Hex[0xC], Decimal[12]
    ModifyItemInventory, // Hex[0xD], Decimal[13]
    ItemChangeObject, // Hex[0xE], Decimal[14]
    SendLock, // Hex[0xF], Decimal[15]
    SendItemDatabaseData, // Hex[0x10], Decimal[16]
    SendParticleEffect, // Hex[0x11], Decimal[17]
    SetIconState, // Hex[0x12], Decimal[18]
    ItemEffect, // Hex[0x13], Decimal[19]
    SetCharacterState, // Hex[0x14], Decimal[20]
    PingReply, // Hex[0x15], Decimal[21]
    PingRequest, // Hex[0x16], Decimal[22]
    GotPunched, // Hex[0x17], Decimal[23]
    AppCheckResponse, // Hex[0x18], Decimal[24]
    AppIntegrityFail, // Hex[0x19], Decimal[25]
    Disconnect, // Hex[0x1A], Decimal[26]
    BattleJoin, // Hex[0x1B], Decimal[27]
    BattleEven, // Hex[0x1C], Decimal[28]
    UseDoor, // Hex[0x1D], Decimal[29]
    SendParental, // Hex[0x1E], Decimal[30]
    GoneFishin, // Hex[0x1F], Decimal[31]
    Steam, // Hex[0x20], Decimal[32]
    PetBattle, // Hex[0x21], Decimal[33]
    Npc, // Hex[0x22], Decimal[34]
    Special, // Hex[0x23], Decimal[35]
    SendParticleEffectV2, // Hex[0x24], Decimal[36]
    ActiveArrowToItem, // Hex[0x25], Decimal[37]
    SelectTileIndex, // Hex[0x26], Decimal[38]
    SendPlayerTributeData, // Hex[0x27], Decimal[39]
    SetExtraMods, // Hex[0x28], Decimal[40]
    OnStepOnTileMod // Hex[0x29], Decimal[41]
}